workers:
    docker_compose: ~
    sass:
        cmd: ['symfony', 'console', 'sass:build', '--watch']
    tailwind_app:
        cmd: ['symfony', 'console', 'tailwind:build', '--watch', 'assets/styles/app-tailwind.css']
    tailwind_toolkit_shadcn:
        cmd: ['symfony', 'console', 'tailwind:build', '--watch', 'assets/styles/toolkit-shadcn.css']

http:
    port: 9044
    use_gzip: true
